(function () {
  const languages = {
    nb: {
      title: "Bruksanvisning", intro: "En kort guide til å opprette, delta i og følge en Padelstar-turnering.", back: "Tilbake til Padelstar", language: "Språk", admin: "For admin", adminText: "Logg inn, velg Opprett og fyll inn turneringsnavn, antall baner og eventuelle spillere. Når turneringen er opprettet, deler du invitasjonskoden eller lenken.", adminSteps: "Legg til eller rediger spillere og banenavn under Styring. Start neste runde når spillerne er klare, registrer resultater og åpne lagrede turneringer igjen fra startsiden.", player: "For spiller med profil", playerText: "Logg inn på Konto og lagre visningsnavnet ditt én gang. Bruk deretter Bli med og invitasjonskoden. Profilnavnet foreslås automatisk neste gang, og statistikken kan følge profilen din.", guest: "For gjestespiller", guestText: "Velg Bli med, skriv inn invitasjonskoden og et navn. Du trenger ikke konto, men gjestedata er bare knyttet til den aktuelle turneringen.", spectator: "For tilskuer", spectatorText: "Åpne tilskuerlenken eller velg TV Mode for en lesbar visning av kamper, baner og resultater.", help: "Tips", helpText: "Admin må være innlogget for å opprette og administrere en live-turnering. Ved dårlig forbindelse kan du vente til Online vises før du lagrer eller sender et resultat." },
    nn: { title: "Brukarrettleiing", intro: "Ein kort guide til å opprette, delta i og følgje ein Padelstar-turnering.", back: "Tilbake til Padelstar", language: "Språk", admin: "For admin", adminText: "Logg inn, vel Opprett og fyll inn turneringsnamn, tal på baner og eventuelle spelarar. Når turneringa er oppretta, deler du invitasjonskoden eller lenkja.", adminSteps: "Legg til eller rediger spelarar og banenamn under Styring. Start neste runde når spelarane er klare, registrer resultat og opne lagra turneringar igjen frå startsida.", player: "For spelar med profil", playerText: "Logg inn på Konto og lagre visningsnamnet ditt éin gong. Bruk deretter Bli med og invitasjonskoden. Profilnamnet blir føreslått automatisk neste gong, og statistikken kan følgje profilen din.", guest: "For gjestespelar", guestText: "Vel Bli med, skriv inn invitasjonskoden og eit namn. Du treng ikkje konto, men gjestedata er berre knytt til den aktuelle turneringa.", spectator: "For tilskodar", spectatorText: "Opne tilskodarlenkja eller vel TV Mode for ei lesbar visning av kampar, baner og resultat.", help: "Tips", helpText: "Admin må vere innlogga for å opprette og administrere ei live-turnering. Ved dårleg samband kan du vente til Online viser før du lagrar eller sender eit resultat." },
    en: { title: "Quick guide", intro: "A short guide to creating, joining and following a Padelstar tournament.", back: "Back to Padelstar", language: "Language", admin: "For admins", adminText: "Sign in, choose Create, and enter the tournament name, number of courts and any players. When the tournament is created, share the invite code or link.", adminSteps: "Add or edit players and court names under Control. Start the next round when players are ready, record results and reopen saved tournaments from the home page.", player: "For players with a profile", playerText: "Sign in under Profile and save your display name once. Then choose Join and enter the invite code. Your profile name is suggested next time, and your statistics can follow your profile.", guest: "For guest players", guestText: "Choose Join, enter the invite code and a name. No account is needed, but guest data is tied only to the current tournament.", spectator: "For spectators", spectatorText: "Open the spectator link or choose TV Mode for a clear view of matches, courts and results.", help: "Tip", helpText: "The admin must be signed in to create and manage a live tournament. If the connection is unstable, wait until Online is shown before saving or submitting a result." },
    es: { title: "Guía rápida", intro: "Una guía breve para crear, unirse y seguir un torneo de Padelstar.", back: "Volver a Padelstar", language: "Idioma", admin: "Para administradores", adminText: "Inicia sesión, elige Crear e indica el nombre del torneo, el número de pistas y los jugadores. Después, comparte el código o enlace de invitación.", adminSteps: "Añade o edita jugadores y nombres de pistas en Control. Inicia la siguiente ronda cuando estén listos, registra resultados y vuelve a abrir torneos guardados desde el inicio.", player: "Para jugadores con perfil", playerText: "Inicia sesión en Perfil y guarda tu nombre una vez. Después elige Unirse e introduce el código. Tu nombre de perfil se propondrá la próxima vez y tus estadísticas pueden seguir tu perfil.", guest: "Para jugadores invitados", guestText: "Elige Unirse, introduce el código y un nombre. No necesitas cuenta, pero los datos del invitado solo pertenecen al torneo actual.", spectator: "Para espectadores", spectatorText: "Abre el enlace de espectador o elige TV Mode para ver partidos, pistas y resultados.", help: "Consejo", helpText: "El administrador debe iniciar sesión para crear y gestionar un torneo en vivo. Si la conexión es inestable, espera a que aparezca Online antes de guardar o enviar un resultado." },
    de: { title: "Kurzanleitung", intro: "Eine kurze Anleitung zum Erstellen, Beitreten und Verfolgen eines Padelstar-Turniers.", back: "Zurück zu Padelstar", language: "Sprache", admin: "Für Admins", adminText: "Melde dich an, wähle Erstellen und gib Turniername, Platzanzahl und Spieler ein. Teile danach den Einladungscode oder Link.", adminSteps: "Füge Spieler und Platznamen unter Steuerung hinzu oder bearbeite sie. Starte die nächste Runde, erfasse Ergebnisse und öffne gespeicherte Turniere wieder über die Startseite.", player: "Für Spieler mit Profil", playerText: "Melde dich unter Profil an und speichere deinen Anzeigenamen einmal. Wähle danach Beitreten und gib den Einladungscode ein. Dein Profilname wird beim nächsten Mal vorgeschlagen.", guest: "Für Gastspieler", guestText: "Wähle Beitreten und gib Code und Namen ein. Ein Konto ist nicht nötig; die Gastdaten gehören nur zum aktuellen Turnier.", spectator: "Für Zuschauer", spectatorText: "Öffne den Zuschauerlink oder wähle TV Mode für eine klare Ansicht von Spielen, Plätzen und Ergebnissen.", help: "Tipp", helpText: "Der Admin muss angemeldet sein, um ein Live-Turnier zu erstellen und zu verwalten. Warte bei einer instabilen Verbindung, bis Online angezeigt wird." },
    fr: { title: "Guide rapide", intro: "Un guide court pour créer, rejoindre et suivre un tournoi Padelstar.", back: "Retour à Padelstar", language: "Langue", admin: "Pour les admins", adminText: "Connectez-vous, choisissez Créer et indiquez le nom du tournoi, le nombre de terrains et les joueurs. Partagez ensuite le code ou le lien d’invitation.", adminSteps: "Ajoutez ou modifiez les joueurs et les noms des terrains dans Contrôle. Lancez la manche suivante, saisissez les résultats et rouvrez les tournois enregistrés depuis l’accueil.", player: "Pour les joueurs avec profil", playerText: "Connectez-vous dans Profil et enregistrez votre nom une fois. Choisissez ensuite Rejoindre et saisissez le code. Votre nom de profil sera proposé la prochaine fois.", guest: "Pour les joueurs invités", guestText: "Choisissez Rejoindre, saisissez le code et un nom. Aucun compte n’est nécessaire, mais les données invité restent liées au tournoi actuel.", spectator: "Pour les spectateurs", spectatorText: "Ouvrez le lien spectateur ou choisissez TV Mode pour voir clairement les matchs, terrains et résultats.", help: "Astuce", helpText: "L’admin doit être connecté pour créer et gérer un tournoi en direct. Si la connexion est instable, attendez qu’Online s’affiche avant d’enregistrer ou d’envoyer un résultat." }
  };
  const lang = localStorage.getItem("padelstar-language") || "nb";
  const copy = languages[lang] || languages.nb;
  document.documentElement.lang = lang;
  document.querySelectorAll("[data-guide-i18n]").forEach((node) => { const key = node.dataset.guideI18n; if (copy[key]) node.textContent = copy[key]; });
  const selector = document.getElementById("guideLanguage");
  if (selector) { selector.value = languages[lang] ? lang : "nb"; selector.addEventListener("change", () => { localStorage.setItem("padelstar-language", selector.value); location.reload(); }); }
})();
