(() => {
  const storageKey = "padelstar-language";
  const translations = {
    nb: {
      back: "Tilbake til Padelstar", language: "Språk", beta: "Beta", title: "Personvern",
      intro: "Padelstar er en beta for å opprette og følge små padelturneringer. Denne teksten beskriver hva løsningen lagrer, hvorfor det lagres, hvor det lagres og hvilke rettigheter du har.",
      responsible: "Hvem er ansvarlig?", responsibleText: "Foreløpig behandlingsansvarlig for betaen er Sigurd Steen Grødem / Zigonia IT. Kontakt for personvernspørsmål er",
      data: "Hvilke opplysninger brukes?", dataText: "Appen kan lagre turneringsnavn, invitasjonskode, spillernavn, avatarvalg, kampoppsett, resultater, rollevalg, tekniske revisjoner, lokal brukerprofil og sikkerhetstokens for admin/spiller. Admin-token deles ikke i offentlig turneringsstate eller backup. Spillertoken brukes for å beskytte spillerstyrt poengføring.",
      why: "Hvorfor brukes opplysningene?", whyText: "Opplysningene brukes for å administrere turneringen, vise riktige kamper og resultater, synkronisere mellom enheter, foreslå spillerens navn/avatar, beskytte skrivehandlinger og gjenopprette siste lokale state ved nettverks- eller lagringsfeil.",
      storage: "Hvor lagres data?", storageText: "Lokalt lagres turneringsstate, språkvalg, brukerprofil og profilhistorikk i nettleseren med localStorage, en siste-kjente-gode kopi og IndexedDB-speiling der nettleseren støtter det. Når live sync eller profilhistorikk er aktivert, lagres nødvendig delt data i Supabase. Statiske filer leveres fra Vercel, og Vercel Analytics kan brukes til enkel trafikkmåling.",
      retention: "Lagringstid og sletting", retentionText: "Anonyme turneringer slettes innen 30 dager etter at admin avslutter turneringen. Gjestedeltakeres identitet, statistikk og kamp-/annen historikk fjernes fra lagret turneringsstate ved avslutning; registrerte spillere og admin kan beholde historikk. Spillerøkter og token-hasher slettes sammen med turneringen. Profilhistorikk kan beholdes lenger mens profilen består; ved profilsletting slettes tilknyttet historikk innen 30 dager. Lokale data kan fjernes ved å nullstille turneringen, slette profilen eller tømme nettleserdata.",
      choices: "Dine valg", choicesText: "Spillere bør bare bruke navn de er komfortable med at andre i turneringen ser. Be arrangøren eller behandlingsansvarlig om innsyn, retting eller sletting dersom noe er feil eller ikke lenger skal brukes.",
      status: "Status", statusText: "Admin kan valgfritt bruke Supabase Auth med innloggingslenke for å knytte en turnering til en konto. Spillere kan opprette en lokal profil med visningsnavn og avatar, og kan valgfritt samtykke til lokale varsler på enheten. Profilen og varslene kan slettes eller slås av igjen i spillerflaten.",
      updated: "Sist oppdatert 2026-09-01. Dette er fortsatt en beta-tekst og bør kvalitetssikres av behandlingsansvarlig før bred bruk. Vercel Analytics beholdes foreløpig for aggregert trafikkmåling.",
    },
    nn: {
      back: "Tilbake til Padelstar", language: "Språk", beta: "Beta", title: "Personvern",
      intro: "Padelstar er ein beta for å opprette og følgje små padelturneringar. Denne teksten skildrar kva løysinga lagrar, kvifor det blir lagra, kvar det blir lagra og kva rettar du har.", responsible: "Kven er ansvarleg?", responsibleText: "Førebels behandlingsansvarleg for betaen er Sigurd Steen Grødem / Zigonia IT. Kontakt for personvernspørsmål er", data: "Kva opplysningar blir brukte?", dataText: "Appen kan lagre turneringsnamn, invitasjonskode, spelarnamn, avatarval, kampoppsett, resultat, rolleval, tekniske revisjonar, lokal brukarprofil og tryggingstoken for admin/spelar. Admin-token blir ikkje delt i offentleg turneringsstate eller backup. Spelartoken vernar spelarstyrt poengføring.", why: "Kvifor blir opplysningane brukte?", whyText: "Opplysningane blir brukte til å administrere turneringa, vise kampar og resultat, synkronisere mellom einingar, føreslå namn/avatar, verne skrivehandlingar og gjenopprette siste lokale state ved nettverks- eller lagringsfeil.", storage: "Kvar blir data lagra?", storageText: "Lokalt blir turneringsstate, språkval, brukarprofil og profilhistorikk lagra i nettlesaren med localStorage, ein siste-kjende-gode kopi og IndexedDB-spegl­ing der nettlesaren støttar det. Når live sync eller profilhistorikk er aktivert, blir nødvendig delt data lagra i Supabase. Statiske filer blir leverte frå Vercel, og Vercel Analytics kan brukast til enkel trafikkmåling.", retention: "Lagringstid og sletting", retentionText: "Anonyme turneringar blir sletta innan 30 dagar etter at admin avsluttar turneringa. Spelarøkter og token-hashar blir sletta saman med turneringa. Profilhistorikk kan haldast lenger medan profilen finst; ved profilsletting blir tilknytt historikk sletta innan 30 dagar. Lokale data kan fjernast ved å nullstille turneringa, slette profilen eller tømme nettlesardata.", choices: "Dine val", choicesText: "Spelarar bør berre bruke namn dei er komfortable med at andre i turneringa ser. Be arrangøren eller behandlingsansvarleg om innsyn, retting eller sletting dersom noko er feil eller ikkje lenger skal brukast.", status: "Status", statusText: "Admin kan valfritt bruke Supabase Auth med innloggingslenkje for å knyte ei turnering til ein konto. Spelarar kan opprette ein lokal profil med visingsnamn og avatar, og kan valfritt samtykkje til lokale varslingar på eininga. Profilen og varslingane kan slettast eller slåast av att i spelarflata.", updated: "Sist oppdatert 2026-09-01. Dette er framleis ein beta-tekst og bør kvalitetssikrast av behandlingsansvarleg før brei bruk. Vercel Analytics blir førebels halde att for aggregert trafikkmåling.",
    },
    en: {
      back: "Back to Padelstar", language: "Language", beta: "Beta", title: "Privacy", intro: "Padelstar is a beta for creating and following small padel tournaments. This notice explains what the service stores, why it is stored, where it is stored, and what rights you have.", responsible: "Who is responsible?", responsibleText: "The provisional controller for the beta is Sigurd Steen Grødem / Zigonia IT. For privacy questions, contact", data: "What information is used?", dataText: "The app may store tournament names, invite codes, player names, avatar choices, match schedules, results, role choices, technical revisions, a local user profile, and admin/player security tokens. Admin tokens are not included in public tournament state or backups. Player tokens protect player-controlled scoring.", why: "Why is the information used?", whyText: "The information is used to administer tournaments, show correct matches and results, synchronize between devices, suggest a player name/avatar, protect write actions, and recover the latest local state after network or storage errors.", storage: "Where is data stored?", storageText: "Tournament state, language choice, user profile, and profile history are stored locally in the browser using localStorage, a last-known-good copy, and IndexedDB mirroring where supported. When live sync or profile history is enabled, necessary shared data is stored in Supabase. Static files are served by Vercel, and Vercel Analytics may be used for basic traffic measurement.", retention: "Retention and deletion", retentionText: "Anonymous tournaments are deleted within 30 days after an admin ends the tournament. Player sessions and token hashes are deleted with the tournament. Profile history may be retained while the profile exists; when a profile is deleted, related history is deleted within 30 days. Local data can be removed by resetting the tournament, deleting the profile, or clearing browser data.", choices: "Your choices", choicesText: "Players should only use names they are comfortable sharing with others in the tournament. Ask the organizer or controller for access, correction, or deletion if information is wrong or no longer needed.", status: "Status", statusText: "Admins may optionally use Supabase Auth with a sign-in link to associate a tournament with an account. Players may create a local profile with a display name and avatar and optionally consent to local device notifications. The profile and notifications can be deleted or disabled in the player view.", updated: "Last updated 2026-09-01. This remains beta text and should be reviewed by the controller before broad use. Vercel Analytics is retained provisionally for aggregated traffic measurement.",
    },
    es: {
      back: "Volver a Padelstar", language: "Idioma", beta: "Beta", title: "Privacidad", intro: "Padelstar es una beta para crear y seguir pequeños torneos de pádel. Este aviso explica qué almacena el servicio, por qué, dónde y qué derechos tienes.", responsible: "¿Quién es responsable?", responsibleText: "El responsable provisional de la beta es Sigurd Steen Grødem / Zigonia IT. Para preguntas de privacidad, contacta con", data: "¿Qué información se utiliza?", dataText: "La aplicación puede almacenar nombres de torneos, códigos de invitación, nombres de jugadores, avatares, partidos, resultados, roles, revisiones técnicas, un perfil local y tokens de seguridad de administrador/jugador. Los tokens de administrador no aparecen en el estado público ni en copias de seguridad. Los tokens de jugador protegen la puntuación controlada por jugadores.", why: "¿Por qué se utiliza la información?", whyText: "Se utiliza para administrar torneos, mostrar partidos y resultados correctos, sincronizar dispositivos, sugerir nombre/avatar, proteger acciones de escritura y recuperar el último estado local tras errores de red o almacenamiento.", storage: "¿Dónde se almacenan los datos?", storageText: "El estado del torneo, idioma, perfil e historial se almacenan localmente en el navegador mediante localStorage, una copia válida conocida e IndexedDB cuando está disponible. Con sincronización o historial activos, los datos compartidos necesarios se almacenan en Supabase. Vercel sirve los archivos estáticos y Vercel Analytics puede medir el tráfico básico.", retention: "Conservación y eliminación", retentionText: "Los torneos anónimos se eliminan en 30 días después de que el administrador los cierre. Las sesiones y hashes de tokens se eliminan con el torneo. El historial puede conservarse mientras exista el perfil; al eliminarlo, el historial asociado se elimina en 30 días. Los datos locales se pueden borrar reiniciando el torneo, eliminando el perfil o limpiando el navegador.", choices: "Tus opciones", choicesText: "Los jugadores solo deben usar nombres que acepten compartir con los demás. Pide acceso, corrección o eliminación al organizador o responsable si los datos son incorrectos o ya no son necesarios.", status: "Estado", statusText: "Los administradores pueden usar Supabase Auth con un enlace de acceso para asociar un torneo a una cuenta. Los jugadores pueden crear un perfil local y aceptar opcionalmente notificaciones del dispositivo. El perfil y las notificaciones se pueden eliminar o desactivar en la vista del jugador.", updated: "Última actualización 2026-09-01. Este texto sigue siendo beta y debe revisarlo el responsable antes de un uso amplio. Vercel Analytics se conserva provisionalmente para medición agregada.",
    },
    de: {
      back: "Zurück zu Padelstar", language: "Sprache", beta: "Beta", title: "Datenschutz", intro: "Padelstar ist eine Beta zum Erstellen und Verfolgen kleiner Padel-Turniere. Diese Erklärung beschreibt, welche Daten gespeichert werden, warum und wo, sowie deine Rechte.", responsible: "Wer ist verantwortlich?", responsibleText: "Der vorläufig Verantwortliche für die Beta ist Sigurd Steen Grødem / Zigonia IT. Bei Datenschutzfragen kontaktiere", data: "Welche Informationen werden verwendet?", dataText: "Die App kann Turniernamen, Einladungscodes, Spielernamen, Avatare, Spielpläne, Ergebnisse, Rollen, technische Revisionen, ein lokales Nutzerprofil und Sicherheits-Tokens für Admins/Spieler speichern. Admin-Tokens sind nicht in öffentlichem Turnierstatus oder Backups enthalten. Spieler-Tokens schützen die spielergesteuerte Punktevergabe.", why: "Warum werden die Informationen verwendet?", whyText: "Die Daten dienen der Turnierverwaltung, der Anzeige korrekter Spiele und Ergebnisse, der Synchronisierung zwischen Geräten, Namens-/Avatarvorschlägen, dem Schutz von Schreibaktionen und der Wiederherstellung des letzten lokalen Zustands.", storage: "Wo werden Daten gespeichert?", storageText: "Turnierstatus, Sprache, Nutzerprofil und Profilhistorie werden lokal im Browser mit localStorage, einer letzten gültigen Kopie und IndexedDB-Spiegelung gespeichert, sofern unterstützt. Bei aktivierter Synchronisierung oder Profilhistorie werden notwendige gemeinsame Daten in Supabase gespeichert. Vercel liefert statische Dateien; Vercel Analytics kann den einfachen Datenverkehr messen.", retention: "Aufbewahrung und Löschung", retentionText: "Anonyme Turniere werden innerhalb von 30 Tagen nach dem Beenden durch den Admin gelöscht. Spielersitzungen und Token-Hashes werden mit dem Turnier gelöscht. Profilhistorie kann bestehen, solange das Profil besteht; bei Löschung wird die zugehörige Historie innerhalb von 30 Tagen gelöscht. Lokale Daten können durch Zurücksetzen des Turniers, Löschen des Profils oder Browserdaten entfernt werden.", choices: "Deine Wahlmöglichkeiten", choicesText: "Spieler sollten nur Namen verwenden, deren Anzeige für andere Turnierteilnehmer in Ordnung ist. Bitte den Veranstalter oder Verantwortlichen um Auskunft, Berichtigung oder Löschung, wenn Daten falsch oder nicht mehr erforderlich sind.", status: "Status", statusText: "Admins können optional Supabase Auth mit einem Anmeldelink verwenden, um ein Turnier einem Konto zuzuordnen. Spieler können ein lokales Profil erstellen und optional Gerätemitteilungen erlauben. Profil und Mitteilungen können in der Spieleransicht gelöscht oder deaktiviert werden.", updated: "Zuletzt aktualisiert: 2026-09-01. Dieser Text ist weiterhin Beta und sollte vor einer breiten Nutzung vom Verantwortlichen geprüft werden. Vercel Analytics bleibt vorläufig für aggregierte Messungen aktiv.",
    },
    fr: {
      back: "Retour à Padelstar", language: "Langue", beta: "Bêta", title: "Confidentialité", intro: "Padelstar est une bêta pour créer et suivre de petits tournois de padel. Cet avis décrit les données stockées, les raisons, le lieu de stockage et vos droits.", responsible: "Qui est responsable ?", responsibleText: "Le responsable provisoire de la bêta est Sigurd Steen Grødem / Zigonia IT. Pour toute question de confidentialité, contactez", data: "Quelles informations sont utilisées ?", dataText: "L’application peut stocker les noms de tournois, codes d’invitation, noms de joueurs, avatars, matchs, résultats, rôles, révisions techniques, un profil local et des jetons de sécurité admin/joueur. Les jetons admin ne figurent pas dans l’état public ni les sauvegardes. Les jetons joueur protègent le score saisi par le joueur.", why: "Pourquoi ces informations sont-elles utilisées ?", whyText: "Elles servent à gérer les tournois, afficher les matchs et résultats corrects, synchroniser les appareils, proposer un nom/avatar, protéger les écritures et restaurer le dernier état local après une erreur réseau ou de stockage.", storage: "Où les données sont-elles stockées ?", storageText: "L’état du tournoi, la langue, le profil et l’historique sont stockés localement dans le navigateur avec localStorage, une copie valide et IndexedDB si disponible. Avec la synchronisation ou l’historique activé, les données partagées nécessaires sont stockées dans Supabase. Vercel sert les fichiers statiques et Vercel Analytics peut mesurer le trafic de base.", retention: "Conservation et suppression", retentionText: "Les tournois anonymes sont supprimés sous 30 jours après leur clôture par l’admin. Les sessions et hash de jetons sont supprimés avec le tournoi. L’historique peut être conservé tant que le profil existe ; après suppression du profil, l’historique associé est supprimé sous 30 jours. Les données locales peuvent être supprimées en réinitialisant le tournoi, en supprimant le profil ou les données du navigateur.", choices: "Vos choix", choicesText: "Les joueurs ne doivent utiliser que des noms qu’ils acceptent de partager avec les autres. Demandez l’accès, la correction ou la suppression à l’organisateur ou au responsable si les données sont erronées ou inutiles.", status: "Statut", statusText: "Les admins peuvent utiliser Supabase Auth avec un lien de connexion pour associer un tournoi à un compte. Les joueurs peuvent créer un profil local et accepter facultativement les notifications de l’appareil. Le profil et les notifications peuvent être supprimés ou désactivés dans la vue joueur.", updated: "Dernière mise à jour : 2026-09-01. Ce texte reste une version bêta et doit être révisé par le responsable avant une utilisation large. Vercel Analytics est conservé provisoirement pour des mesures agrégées.",
    },
  };

  const language = () => {
    const stored = localStorage.getItem(storageKey);
    return translations[stored] ? stored : "nb";
  };

  function apply(languageCode) {
    const selected = translations[languageCode] ? languageCode : "nb";
    const strings = translations[selected];
    document.documentElement.lang = selected === "nb" ? "no" : selected;
    document.title = `${strings.title} - Padelstar`;
    document.querySelectorAll("[data-privacy-i18n]").forEach((node) => {
      const value = strings[node.dataset.privacyI18n];
      if (value) node.textContent = value;
    });
    document.querySelectorAll("[data-privacy-aria-label]").forEach((node) => {
      const value = strings[node.dataset.privacyAriaLabel];
      if (value) node.setAttribute("aria-label", value);
    });
    const select = document.querySelector("#privacyLanguage");
    if (select) select.value = selected;
  }

  const select = document.querySelector("#privacyLanguage");
  select?.addEventListener("change", () => {
    localStorage.setItem(storageKey, select.value);
    apply(select.value);
  });
  apply(language());
})();
